project:
  type: website

website:
  navbar:
    background: primary
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
    search: false
    left:
      - text: "Home"
        file: index.ipynb
      - talks.qmd
      - about.qmd