project:
  type: website
  output-dir: .

website:
  navbar:
    background: primary
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        href: https://github.com/Simontagbor
      - icon: kaggle
        href: https://www.kaggle.com/simontagbor
        menu:
          - text: Source Code
            url:  https://github.com/Simontagbor/BritishAirways-predictive-ML
          - text: Report a Bug
            url:  https://bugs.com
    left:
      - text: "Simon's Notes"
        file: index.ipynb